### ISSUE TITLE
Rails 5 compatibility

### ISSUE THREAD

**Issue by oyeanuj** [KevinBongart/valid_attribute#2]
Hi @KevinBongart, thank you for open sourcing this! I was wondering if Rails 5 compatibility was on the radar for the library?

**Comment by KevinBongart** [comment]
Hi @oyeanuj, just like https://github.com/KevinBongart/join_cache/issues/5#issuecomment-326837732 this gem is not officially maintained. Though much better implemented than `join_cache`, it might be compatible with Rails 5 already.

I'll let you test it out, and report issues you find. Thanks!

**Comment by oyeanuj** [comment]
@KevinBongart Thank you for the quick response. I just added a PR (#3) to make it compatible.
